# Read the documentation before extending the defaults:
# https://docs.searxng.org/admin/settings/

use_default_settings: true

server:
  secret_key: "4uVZ7CVCjzuOg5spOLyeG2Lpf9b97aYF"
  image_proxy: true

search:
  formats:
    - html
    - json

engines:
  - name: brave
    engine: brave
    weight: 1.5
    shortcut: br
  - name: duckduckgo
    engine: duckduckgo
    weight: 1.2
    shortcut: ddg
  - name: google
    engine: google
    weight: 1.5
    use_mobile_ui: false
  - name: wikidata
    disabled: true   # Tắt nếu bị lỗi 403 liên tục