# Read the documentation before extending the defaults:
# https://docs.searxng.org/admin/settings/

use_default_settings: true

server:
  secret_key: "AsD26ryLTFhUGeA6HlQZmsX1h05W"
  image_proxy: true
  limiter: false

search:
  formats:
    - html
    - json
